services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
test:
  adapter: postgresql
  database: travis_ci_test
language: ruby
rvm:
  - 2.5.1
