sudo: true
env:
  global:
    - RAILS_ENV=test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake
install:
  - bundle install
  - nvm install stable && nvm alias default stable
  - npm install -g npm@5.6.x
  - npm install -g yarn
  - node --version
  - npm --version
  - yarn install
test:
  adapter: postgresql
  database: travis_ci_test
language: ruby
rvm:
  - 2.5.1
